# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n7Pl7uiMGgQSr72bPtjQZ8F9_ra8AyKF
"""

import pandas as pd
import numpy as np
from sklearn.linear_model import PassiveAggressiveClassifier

data=pd.read_csv("/content/drive/MyDrive/news.csv")
data

data.head()

data.shape

data=data.dropna()

data['text']=data['text'].astype(str)

def remove_punctuation(text):
  import string
  remover=str.maketrans('','',string.punctuation)
  return text.translate(remover)

data['text']=data['text'].apply(remove_punctuation)
data.head()

import nltk
 nltk.download('stopwords')

from nltk.corpus import stopwords
stop_words=stopwords.words("english")

def remove_stopwords(text):
  text = [word.lower() for word in text.split() if word.lower() not in stop_words]
  return " ".join(text)

data['text']=data['text'].apply(remove_stopwords)
data.head()

data['label']=np.where(data['label']=='REAL',1,0)

data.head()

x=data['text']
x

y=data['label']
y

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

from sklearn.feature_extraction.text import TfidfVectorizer
tfidvec=TfidfVectorizer()
tfidx_train=tfidvec.fit_transform(x_train)
tfidx_test=tfidvec.transform(x_test)

pac=PassiveAggressiveClassifier()
pac.fit(tfidx_train,y_train)

pac_pred=pac.predict(tfidx_test)
pac_pred

from sklearn.metrics import accuracy_score
ascore=accuracy_score(y_test,pac_pred)
ascore

from sklearn.metrics import confusion_matrix
report=confusion_matrix(y_test,pac_pred)
report

